/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:3ebb7a27-6653-41ce-a634-7ec42f246ccb",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_psWIeIYCB",
    "aws_user_pools_web_client_id": "3v5mb6bv7nmvf2a2db0cafuvbh",
    "oauth": {}
};


export default awsmobile;
